services:
  pg-database:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mimiciii
    volumes:
      # rw: permissions to read and write
      - "c:/ZoomCamp/data-engineering/module_1/mimiciii_data:/var/lib/postgresql/data:rw"
    ports:
      - 5430:5432

  pg-admin4:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
